import { zipSync, unzipSync, strToU8, strFromU8 } from 'fflate';
import { downloadBlob } from './download';
import type { NetworkConfig, Peer } from './types';

interface ZipEntry {
  filename: string;
  content: string;
}

export function downloadZip(entries: ZipEntry[], zipFilename: string): void {
  const files: Record<string, Uint8Array> = {};
  for (const entry of entries) {
    files[entry.filename] = strToU8(entry.content);
  }
  const zipped = zipSync(files);
  const blob = new Blob([zipped], { type: 'application/zip' });
  downloadBlob(blob, zipFilename);
}

export interface ImportResult {
  network: NetworkConfig;
  peers: Peer[];
}

export function parseImportZip(buffer: ArrayBuffer): ImportResult {
  const bytes = new Uint8Array(buffer);
  const files = unzipSync(bytes);

  // Prefer metadata.json for full fidelity
  const metaRaw = files['metadata.json'];
  if (metaRaw) {
    return JSON.parse(strFromU8(metaRaw)) as ImportResult;
  }

  return parseFallback(files);
}

// Fallback parser for zips without metadata.json (e.g. generated by other tools).
//
// A node's own public endpoint is NOT present in its own .conf — it only appears
// in OTHER nodes' [Peer] blocks. We cross-reference all conf files to reconstruct
// each peer's publicEndpointIp and publicKey correctly.
function parseFallback(
  files: Record<string, Uint8Array>,
): ImportResult {
  const network: NetworkConfig = {
    subnet: '10.100.0',
    port: 51820,
    keepalive: 25,
    topology: 'mesh',
  };

  // octet → mutable peer record
  const byOctet = new Map<number, Peer>();

  // Pass 1: parse each peer's own [Interface] section
  for (const [filename, raw] of Object.entries(files)) {
    if (!filename.endsWith('.conf')) continue;
    const text = strFromU8(raw);
    const name = filename.replace('.conf', '');

    const subnetMatch = text.match(/Address\s*=\s*(\d+\.\d+\.\d+)\.\d+\/\d+/);
    if (subnetMatch) network.subnet = subnetMatch[1];

    const portMatch = text.match(/ListenPort\s*=\s*(\d+)/);
    if (portMatch) network.port = parseInt(portMatch[1], 10);

    // Take the lowest keepalive seen (most restrictive)
    const keepMatch = text.match(/PersistentKeepalive\s*=\s*(\d+)/);
    if (keepMatch) {
      const v = parseInt(keepMatch[1], 10);
      if (v < network.keepalive || network.keepalive === 25) network.keepalive = v;
    }

    const octetMatch = text.match(/Address\s*=\s*\d+\.\d+\.\d+\.(\d+)\/\d+/);
    if (!octetMatch) continue;
    const wgOctet = parseInt(octetMatch[1], 10);

    // PrivateKey is in the [Interface] section — take only the first match
    const privMatch = text.match(/PrivateKey\s*=\s*(\S+)/);

    byOctet.set(wgOctet, {
      id: '',
      name,
      label: name,
      lanIp: '',
      publicEndpointIp: '',
      wgOctet,
      keys: { privateKey: privMatch?.[1] ?? '', publicKey: '' },
      role: 'spoke',
      fullTunnel: false,
      natGateway: false,
      natInterface: 'eth0',
    });
  }

  // Pass 2: cross-reference [Peer] blocks across all conf files.
  // Each [Peer] block tells us: peer at <octet> has publicKey <K> and,
  // if Endpoint is present, publicEndpointIp <IP>.
  for (const [filename, raw] of Object.entries(files)) {
    if (!filename.endsWith('.conf')) continue;
    const text = strFromU8(raw);

    // Split on [Peer] markers; index 0 is the [Interface] section
    const sections = text.split(/^\[Peer\]/m).slice(1);
    for (const block of sections) {
      const pubKeyMatch = block.match(/PublicKey\s*=\s*(\S+)/);
      const allowedMatch = block.match(/AllowedIPs\s*=[^\n]*?(\d+\.\d+\.\d+\.(\d+))\/32/);
      if (!pubKeyMatch || !allowedMatch) continue;

      const octet = parseInt(allowedMatch[2], 10);
      const peer = byOctet.get(octet);
      if (!peer) continue;

      if (!peer.keys.publicKey) {
        peer.keys.publicKey = pubKeyMatch[1];
      }

      const endpointMatch = block.match(/Endpoint\s*=\s*([^:\s]+):/);
      if (endpointMatch && !peer.publicEndpointIp) {
        peer.publicEndpointIp = endpointMatch[1];
      }
    }
  }

  // Pass 3: keys.txt can supply public keys that may not appear as [Peer] entries
  const keysTxt = files['keys.txt'];
  if (keysTxt) {
    const text = strFromU8(keysTxt);
    // Each block starts with a non-whitespace peer name
    const blocks = text.split(/\n(?=\S)/).filter(Boolean);
    for (const block of blocks) {
      const pubMatch = block.match(/public\s*:\s*(\S+)/);
      const octetMatch = block.match(/wg ip\s*:.*?(\d+\.\d+\.\d+\.(\d+))\//);
      if (!pubMatch || !octetMatch) continue;
      const octet = parseInt(octetMatch[2], 10);
      const peer = byOctet.get(octet);
      if (peer && !peer.keys.publicKey) {
        peer.keys.publicKey = pubMatch[1];
      }
    }
  }

  // Sort by octet, assign sequential IDs
  const peers = Array.from(byOctet.values())
    .sort((a, b) => a.wgOctet - b.wgOctet)
    .map((p, i) => ({ ...p, id: String(i + 1) }));

  return { network, peers };
}
